### ISSUE TITLE
[Suggestion] Ender Chest Support

### ISSUE THREAD

**Issue by nco2k** [A5b84/held-item-info#25]
would be cool if your mod could also show the content of ender chests.

**Comment by A5b84** [comment]
I don't think this is easily feasible considering this is a client-side mod (I'm pretty sure the server won't tell clients what's in their ender chest until you actually place one and open it) and also ender chests are somewhat special in the sense that their content isn't a property of the item but of the player (two ender chest items will behave the same for a given player), so this isn't a feature planned for the foreseeable future
