### ISSUE TITLE
The text background is white instead of black when holding an item

### ISSUE THREAD

**Issue by furiouswhqle** [A5b84/held-item-info#28]
In accessibility settings, there is an option called "Text Background"
When it's set to "everywhere", and you hold an item, the background is white instead of black.
![without the mod](https://github.com/A5b84/held-item-info/assets/148171479/cc55db0a-7c43-49bf-ab16-bb85e7f1e8fa)
![with the mod](https://github.com/A5b84/held-item-info/assets/148171479/e6dbe43e-7b7d-45c2-be33-39421d4bd76c)

**Comment by furiouswhqle** [comment]
I'm using Minecraft 1.21, Fabric 0.15.11, and 1.6.1 of Held Item Info if that helps

**Comment by A5b84** [comment]
Thanks for the report, that's fiexd in the latest version
