### ISSUE TITLE
1.17 crash when holding a shulker box

### ISSUE THREAD

**Issue by lolleap** [A5b84/held-item-info#4]
Just updated to 1.17 and found that the 1.16 version 1.1.3 was marked to work with 1.17 and it loaded up fine. However when I tried to hold a shulker box with items in the game fully crashed, I have tested this on the server I was on and on a single-player world. I happens with any shulker box with items in. I could have the boxes in my inventory just not in my hand. I have attached a crash report.
[crash-2021-06-09_16.20.07-client.txt](https://github.com/A5b84/held-item-info/files/6625056/crash-2021-06-09_16.20.07-client.txt)

**Comment by spjoes** [comment]
Can confirm. This has happened to me (went to Issues tab just to report this issue and someone already has).

Just incase if one Crash Report/Log isnt enough for whatever reason: https://hastebin.com/ikiyuxades.yaml

**Comment by A5b84** [comment]
I'll update the mod to 1.17 soonish (iirc it was marked compatible with 1.17 because it worked on the first snapshots and curseforge didn't have the '1.17 Snapshots' option)

**Comment by A5b84** [comment]
(Hopefully) fixed in 1.2.0, looks like recompiling was enough
