### ISSUE TITLE
[Suggestion] Hotbar Offset?

### ISSUE THREAD

**Issue by RaptaG** [A5b84/held-item-info#6]
Could you please add that option since the enchantments are only 1 pixel above the armour status

**Comment by A5b84** [comment]
You can set the "Vertical Offset per Extra Line" option to 0 to make the tooltip always be the same distance from the armor bar (this makes me think I should maybe give options better names and/or lower the default value)

**Comment by RaptaG** [comment]
Also, how can I move the Item's name 2 pixels higher?

**Comment by A5b84** [comment]
Right now I don't think there's an option for that

**Comment by A5b84** [comment]
Added in v1.3.0
