### ISSUE TITLE
Suggestion: Add an option to choose which enchantment to show

### ISSUE THREAD

**Issue by EGOIST1372** [A5b84/held-item-info#7]
Add an option to choose which enchantment to show when holding an item
for instance I want when I hold a pickaxe only shows me if its a fortune or silk touch pickaxe and I don't want my screen get cluttered by other enchantment that are not important since only fortune and silk are important when you want break a ender chest or an ore. so it would be great if we could have this level of customization in showing which enchant for each item individually(pickaxe, axe , shovel etc...)
thanks in advance <3

**Comment by A5b84** [comment]
You should already be able to filter enchantments (not for individual items though) by going to the "Enchantment filters" tab, setting "Only Show Filtered Enchantments" to "Yes" and adding `minecraft:fortune` and `minecraft:silk_touch` to the "Filtered Enchantments" list thing using the `+` button on the left
