### ISSUE TITLE
Minecraft 1.19 - Crash anytime tooltips are displayed.

### ISSUE THREAD

**Issue by Neptune-Sky** [A5b84/held-item-info#8]
I know 1.19 isn't shown as the latest supported version, but figured I'd report this anyways to get ahead of others complaining about it.

Any time that tooltips are displayed, regardless of whether enchantments are actually on the item, this crash occurs. Happens with no other mods installed.

https://crashy.net/hHfp9EdQF21okLp8v1Ve

**Comment by A5b84** [comment]
Yup I'm planning on updating the mod in a very near future

**Comment by A5b84** [comment]
Fixed in v1.3.0
